on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Run Detekt linter
        run: ./gradlew detekt

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests with coverage
        run: ./gradlew test jacocoTestReport

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html/

      - name: Run component tests
        run: ./gradlew testComponent

      - name: Upload component test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: component-test-report
          path: build/reports/tests/testComponent/

      - name: Mutation testing with Pitest
        run: ./gradlew pitest

      - name: Upload Pitest report
        uses: actions/upload-artifact@v4
        with:
          name: pitest-report
          path: build/reports/pitest/